server:
  port: 8080  # Puerto donde corre la aplicación

spring:
  application:
    name: tutorialsService

  main:
    allow-bean-definition-overriding: true

  data:
    mongodb:
      uri: mongodb+srv://usuario:usuario@agenda.c9ooj.mongodb.net/tutorialsservice_db?retryWrites=true&w=majority
