server:
  port: 8081  # Puerto donde corre la aplicación

spring:
  application:
    name: demo

  main:
    allow-bean-definition-overriding: true

  data:
    mongodb:
      host: localhost  # Si está en Docker, usar el nombre del servicio en docker-compose
      port: 27017
      database: tutorialsservice_db
